# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InterFaceWindow(object):
    def setupUi(self, InterFaceWindow):
        InterFaceWindow.setObjectName("InterFaceWindow")
        InterFaceWindow.resize(768, 494)
        self.centralwidget = QtWidgets.QWidget(InterFaceWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(768, 474))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(768, 46))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 121, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/数据库查询.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(170, 0))
        self.frame_4.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_logout.setGeometry(QtCore.QRect(0, 10, 75, 24))
        self.pushButton_logout.setStyleSheet("")
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/登出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 10, 75, 24))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 10, 75, 24))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(750, 418))
        self.frame.setStyleSheet("#frame{\n"
"    border-bottom-left-radius:22px;\n"
"    border-bottom-right-radius:20px;\n"
"    \n"
"    background-color: rgb(244, 244, 244);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("#frame_5{\n"
"    background-color: rgb(13, 85, 157);\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \"幼圆\";\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:4px\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_home.setGeometry(QtCore.QRect(4, 30, 141, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/首页白.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_home.setIcon(icon4)
        self.pushButton_home.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_home.setObjectName("pushButton_home")
        self.pushButton_search = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_search.setGeometry(QtCore.QRect(4, 70, 141, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/数据库查询白.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search.setIcon(icon5)
        self.pushButton_search.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("#frame_9{\n"
"borer-bottom-left-radius:20px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_myaccount = QtWidgets.QPushButton(self.frame_9)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/个人信息.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_myaccount.setIcon(icon6)
        self.pushButton_myaccount.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_myaccount.setObjectName("pushButton_myaccount")
        self.verticalLayout_3.addWidget(self.pushButton_myaccount)
        self.pushButton_support = QtWidgets.QPushButton(self.frame_9)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/服务白.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_support.setIcon(icon7)
        self.pushButton_support.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_support.setObjectName("pushButton_support")
        self.verticalLayout_3.addWidget(self.pushButton_support)
        self.pushButton_help = QtWidgets.QPushButton(self.frame_9)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/帮助.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_help.setIcon(icon8)
        self.pushButton_help.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_help.setObjectName("pushButton_help")
        self.verticalLayout_3.addWidget(self.pushButton_help)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"border-bottom-right-radius:20px;\n"
"background-color: rgb(244, 244, 244);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home_page = QtWidgets.QWidget()
        self.page_home_page.setObjectName("page_home_page")
        self.label = QtWidgets.QLabel(self.page_home_page)
        self.label.setGeometry(QtCore.QRect(270, 180, 54, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_home_page)
        self.page_inquire_page = QtWidgets.QWidget()
        self.page_inquire_page.setObjectName("page_inquire_page")
        self.label_2 = QtWidgets.QLabel(self.page_inquire_page)
        self.label_2.setGeometry(QtCore.QRect(280, 180, 54, 16))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_inquire_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_reset_password = QtWidgets.QWidget(self.page)
        self.widget_reset_password.setStyleSheet("QLineEdit{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"    font: 11pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px\n"
"}")
        self.widget_reset_password.setObjectName("widget_reset_password")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_reset_password)
        self.verticalLayout_4.setContentsMargins(150, 80, 170, 170)
        self.verticalLayout_4.setSpacing(100)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_reset_password)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_reset_password)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.pushButton_change_password = QtWidgets.QPushButton(self.widget_reset_password)
        self.pushButton_change_password.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_change_password.setObjectName("pushButton_change_password")
        self.verticalLayout_4.addWidget(self.pushButton_change_password)
        self.stackedWidget_show_reset_error = QtWidgets.QStackedWidget(self.widget_reset_password)
        self.stackedWidget_show_reset_error.setMinimumSize(QtCore.QSize(250, 40))
        self.stackedWidget_show_reset_error.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stackedWidget_show_reset_error.setStyleSheet("font: 700 12pt \"微软雅黑\";\n"
"color: rgb(170, 0, 0);\n"
"")
        self.stackedWidget_show_reset_error.setObjectName("stackedWidget_show_reset_error")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_show_reset_error.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(100, 9, 96, 22))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName("label_3")
        self.stackedWidget_show_reset_error.addWidget(self.page_3)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_6 = QtWidgets.QLabel(self.page_9)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 121, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget_show_reset_error.addWidget(self.page_9)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_5 = QtWidgets.QLabel(self.page_8)
        self.label_5.setGeometry(QtCore.QRect(90, 10, 111, 22))
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_5.setObjectName("label_5")
        self.stackedWidget_show_reset_error.addWidget(self.page_8)
        self.verticalLayout_4.addWidget(self.stackedWidget_show_reset_error)
        self.verticalLayout_7.addWidget(self.widget_reset_password)
        self.stackedWidget.addWidget(self.page)
        self.page_support_page = QtWidgets.QWidget()
        self.page_support_page.setObjectName("page_support_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_support_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.page_support_page)
        self.frame_8.setStyleSheet("#frame_8{\n"
"\n"
"    \n"
"    background-color: rgb(244, 244, 244);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(12, 0, 12, 12)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 181, 61))
        self.pushButton_5.setStyleSheet("\n"
"border:none;\n"
"font: 20pt \"幼圆\";")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/服务.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon9)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.frame_10)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("/*QTabWidget*/\n"
"QTabWidget::pane{\n"
"border:none;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"     left: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     \n"
"    background-color: rgb(255, 255, 255);\n"
"     /*border: 2px solid #C4C4C3;*/\n"
"     border-bottom-color: #C2C7CB;\n"
"     min-width: 60px;\n"
"     padding: 2px;\n"
" }\n"
"\n"
"QTabBar::tab:selected{\n"
"    \n"
"    border-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected{\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    margin-top:5px;\n"
"}\n"
"/*四个下属界面*/\n"
"#tab,#tab_2,#tab_3,#tab_4{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius:20px;\n"
" border-bottom-right-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setContentsMargins(70, 30, 70, 30)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_support_web = QtWidgets.QPushButton(self.tab)
        self.pushButton_support_web.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_support_web.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"    font: 20pt \"幼圆\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/跳转.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_support_web.setIcon(icon10)
        self.pushButton_support_web.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_support_web.setObjectName("pushButton_support_web")
        self.verticalLayout_8.addWidget(self.pushButton_support_web)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setContentsMargins(50, 30, 50, 40)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listWidget_support = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_support.setObjectName("listWidget_support")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_support.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_support.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_support.addItem(item)
        self.verticalLayout_9.addWidget(self.listWidget_support)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_support_page)
        self.page_help_page = QtWidgets.QWidget()
        self.page_help_page.setObjectName("page_help_page")
        self.label_4 = QtWidgets.QLabel(self.page_help_page)
        self.label_4.setGeometry(QtCore.QRect(280, 170, 54, 16))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_help_page)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame)
        InterFaceWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InterFaceWindow)
        self.statusbar.setObjectName("statusbar")
        InterFaceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InterFaceWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_show_reset_error.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(InterFaceWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(InterFaceWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InterFaceWindow)

    def retranslateUi(self, InterFaceWindow):
        _translate = QtCore.QCoreApplication.translate
        InterFaceWindow.setWindowTitle(_translate("InterFaceWindow", "MainWindow"))
        self.pushButton.setText(_translate("InterFaceWindow", "武器系统检索"))
        self.pushButton_home.setText(_translate("InterFaceWindow", "首页"))
        self.pushButton_search.setText(_translate("InterFaceWindow", "查询"))
        self.pushButton_myaccount.setText(_translate("InterFaceWindow", "账号管理"))
        self.pushButton_support.setText(_translate("InterFaceWindow", "支持与服务"))
        self.pushButton_help.setText(_translate("InterFaceWindow", "帮助文档"))
        self.label.setText(_translate("InterFaceWindow", "首页"))
        self.label_2.setText(_translate("InterFaceWindow", "查询"))
        self.lineEdit.setPlaceholderText(_translate("InterFaceWindow", "新密码："))
        self.lineEdit_2.setPlaceholderText(_translate("InterFaceWindow", "确认密码："))
        self.pushButton_change_password.setText(_translate("InterFaceWindow", "确认"))
        self.label_3.setText(_translate("InterFaceWindow", "密码不一致！"))
        self.label_6.setText(_translate("InterFaceWindow", "密码不能为空！"))
        self.label_5.setText(_translate("InterFaceWindow", "密码修改成功"))
        self.pushButton_5.setText(_translate("InterFaceWindow", "支持与服务"))
        self.pushButton_support_web.setText(_translate("InterFaceWindow", "麻花与千层饼"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("InterFaceWindow", "服务网站"))
        __sortingEnabled = self.listWidget_support.isSortingEnabled()
        self.listWidget_support.setSortingEnabled(False)
        item = self.listWidget_support.item(0)
        item.setText(_translate("InterFaceWindow", "WeChat："))
        item = self.listWidget_support.item(1)
        item.setText(_translate("InterFaceWindow", "Email："))
        item = self.listWidget_support.item(2)
        item.setText(_translate("InterFaceWindow", "QQ："))
        self.listWidget_support.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("InterFaceWindow", "联系我们"))
        self.label_4.setText(_translate("InterFaceWindow", "帮助文档"))
import res_rc
