# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatabaseMangeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseMangeUI(object):
    def setupUi(self, DatabaseMangeUI):
        DatabaseMangeUI.setObjectName("DatabaseMangeUI")
        DatabaseMangeUI.resize(800, 500)
        DatabaseMangeUI.setMinimumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/数据库管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DatabaseMangeUI.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DatabaseMangeUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(DatabaseMangeUI)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(12, 0, 12, 12)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_5.setStyleSheet("\n"
"border:none;\n"
"font: 20pt \"幼圆\";")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignLeft)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"    font: 11pt \"微软雅黑\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:\n"
"qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:1,\n"
"stop: 0 rgba(100,100,100,255),\n"
"stop: 0.495 rgba(0,0,0,255),\n"
"stop: 0.505 rgba(0,0,0,255),\n"
"stop: 1 rgba(100,100,100,255));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"padding-left:2px;\n"
"padding-top:1px;\n"
"}\n"
"\n"
"/*QTableView 左上角样式*/\n"
"QTableView QTableCornerButton::section {\n"
"   /*  background: red;\n"
"    border: 2px outset red;*/\n"
"    color: red;\n"
"    background-color: rgb(64, 64, 64);\n"
"    border: 5px solid #f6f7fa;\n"
"    border-radius:0px;\n"
"    border-color: rgb(64, 64, 64);\n"
" }\n"
"\n"
" QTableView {\n"
"    color: white;                                       /*表格内文字颜色*/\n"
"    gridline-color: black;                              /*表格内框颜色*/\n"
"    background-color: rgb(108, 108, 108);               /*表格内背景色*/\n"
"    alternate-background-color: rgb(64, 64, 64);\n"
"    selection-color: white;                             /*选中区域的文字颜色*/\n"
"    selection-background-color: rgb(77, 77, 77);        /*选中区域的背景色*/\n"
"    border: 2px groove gray;\n"
"    border-radius: 0px;\n"
"    padding: 2px 4px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    color: white;\n"
"    font: bold 10pt;\n"
"    background-color: rgb(108, 108, 108);\n"
"    border: 0px solid rgb(144, 144, 144);\n"
"    border:0px solid rgb(191,191,191);\n"
"    border-left-color: rgba(255, 255, 255, 0);\n"
"    border-top-color: rgba(255, 255, 255, 0);\n"
"    border-radius:0px;\n"
"    min-height:29px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: white;\n"
"    background-color: rgb(64, 64, 64);\n"
"    border: 5px solid #f6f7fa;\n"
"    border-radius:0px;\n"
"    border-color: rgb(64, 64, 64);\n"
"} \n"
"\n"
"\n"
"/*表右侧的滑条*/\n"
"QScrollBar:vertical{\n"
"background:#484848;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-width:12px;\n"
"}\n"
"\n"
"/*滑块*/\n"
"QScrollBar::handle:vertical{\n"
"background:#CCCCCC;\n"
"}\n"
"/*\n"
"滑块悬浮，按下*/\n"
"QScrollBar::handle:hover:vertical,QScrollBar::handle:pressed:vertical{\n"
"background:#A7A7A7;\n"
"}\n"
"/*\n"
"滑块已经划过的区域*/\n"
"QScrollBar::sub-page:vertical{\n"
"background:444444;\n"
"}\n"
"\n"
"/*\n"
"滑块还没有划过的区域*/\n"
"QScrollBar::add-page:vertical{\n"
"background:5B5B5B;\n"
"}\n"
"\n"
"/*页面下移的按钮*/\n"
"QScrollBar::add-line:vertical{\n"
"background:none;\n"
"}\n"
"/*页面上移的按钮*/\n"
"QScrollBar::sub-line:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"/*QTabWidget*/\n"
"QTabWidget::pane{\n"
"border:none;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"     left: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     \n"
"    background-color: rgb(255, 255, 255);\n"
"     /*border: 2px solid #C4C4C3;*/\n"
"     border-bottom-color: #C2C7CB;\n"
"     min-width: 60px;\n"
"     padding: 2px;\n"
" }\n"
"\n"
"QTabBar::tab:selected{\n"
"    \n"
"    border-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected{\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    margin-top:5px;\n"
"}\n"
"/*四个下属界面*/\n"
"#tab,#tab_2,#tab_3,#tab_4{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius:20px;\n"
" border-bottom-right-radius:20px;\n"
"border-top-right-radius:20px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.weaponLayout = QtWidgets.QWidget()
        self.weaponLayout.setObjectName("weaponLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.weaponLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.weaponTab = QtWidgets.QTableWidget(self.weaponLayout)
        self.weaponTab.setMinimumSize(QtCore.QSize(0, 0))
        self.weaponTab.setObjectName("weaponTab")
        self.weaponTab.setColumnCount(0)
        self.weaponTab.setRowCount(0)
        self.verticalLayout_2.addWidget(self.weaponTab)
        self.tabWidget.addTab(self.weaponLayout, "")
        self.vehicleLayout = QtWidgets.QWidget()
        self.vehicleLayout.setObjectName("vehicleLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.vehicleLayout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vehicleTab = QtWidgets.QTableWidget(self.vehicleLayout)
        self.vehicleTab.setObjectName("vehicleTab")
        self.vehicleTab.setColumnCount(0)
        self.vehicleTab.setRowCount(0)
        self.verticalLayout_3.addWidget(self.vehicleTab)
        self.tabWidget.addTab(self.vehicleLayout, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.pushButton = QtWidgets.QPushButton(self.frame_8)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius:9px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    \n"
"    font: 11pt \"微软雅黑\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:\n"
"qlineargradient(spread:pad,x1:0,x2:0, y1:0, y2:1,\n"
"stop: 0 rgba(100,100,100,255),\n"
"stop: 0.495 rgba(0,0,0,255),\n"
"stop: 0.505 rgba(0,0,0,255),\n"
"stop: 1 rgba(100,100,100,255));\n"
"color: rgb(255, 255, 255);\n"
"\n"
"padding-left:2px;\n"
"padding-top:1px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_8)

        self.retranslateUi(DatabaseMangeUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DatabaseMangeUI)

    def retranslateUi(self, DatabaseMangeUI):
        _translate = QtCore.QCoreApplication.translate
        DatabaseMangeUI.setWindowTitle(_translate("DatabaseMangeUI", "数据库管理"))
        self.pushButton_5.setText(_translate("DatabaseMangeUI", "数据库管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.weaponLayout), _translate("DatabaseMangeUI", "武器"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vehicleLayout), _translate("DatabaseMangeUI", "载具"))
        self.pushButton.setText(_translate("DatabaseMangeUI", "添加"))
import res_rc
