# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SQLTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SQLTable(object):
    def setupUi(self, SQLTable):
        SQLTable.setObjectName("SQLTable")
        SQLTable.resize(539, 422)
        self.centralwidget = QtWidgets.QWidget(SQLTable)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 10, 471, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(310, 320, 75, 24))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setGeometry(QtCore.QRect(410, 320, 75, 24))
        self.pushButton_load.setObjectName("pushButton_load")
        SQLTable.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SQLTable)
        self.statusbar.setObjectName("statusbar")
        SQLTable.setStatusBar(self.statusbar)

        self.retranslateUi(SQLTable)
        QtCore.QMetaObject.connectSlotsByName(SQLTable)

    def retranslateUi(self, SQLTable):
        _translate = QtCore.QCoreApplication.translate
        SQLTable.setWindowTitle(_translate("SQLTable", "MainWindow"))
        self.pushButton_clear.setText(_translate("SQLTable", "clear"))
        self.pushButton_load.setText(_translate("SQLTable", "load"))
